const StudentProfile = require('../models/StudentProfile');
const { getLearnerInsights } = require('../utils/learnerInsights');
const {
  CONTACT_PROFILE_KEYS,
  validateStudentProfileContactFields,
} = require('../utils/studentProfileFieldValidation');

const USER_POPULATE_FIELDS = 'name email role profilePhoto';

// @desc    Get current user's student profile
// @route   GET /api/profile
// @access  Private
exports.getMyProfile = async (req, res) => {
  try {
    const profile = await StudentProfile.findOne({ user: req.user._id }).populate(
      'user',
      USER_POPULATE_FIELDS
    );

    if (!profile) {
      if (req.user.role === 'student') {
        const insights = await getLearnerInsights(req.user._id);

        return res.status(200).json({
          success: true,
          data: {
            profile: {
              user: {
                _id: req.user._id,
                name: req.user.name,
                email: req.user.email,
                role: req.user.role,
                profilePhoto: req.user.profilePhoto || '',
              },
              bio: '',
              course: '',
              branch: '',
              year: '',
              semester: '',
              studentPhone: '',
              fatherName: '',
              motherName: '',
              fatherPhone: '',
              motherPhone: '',
              address: '',
              city: '',
              state: '',
              pincode: '',
              dateOfBirth: '',
              bloodGroup: '',
              emergencyContactName: '',
              emergencyContactPhone: '',
              toolsAndTechnologies: [],
              visibleToCompanies: true,
              skills: insights.skills,
              stats: insights.stats,
              overallScore: insights.overallScore,
              scoreHistory: insights.scoreHistory,
              isAutoGenerated: true,
            },
          },
          message:
            insights.skills.length || insights.stats.assessmentsTaken || insights.stats.coursesEnrolled
              ? 'Profile was generated from your existing activity.'
              : 'No profile yet. Use POST /api/profile to create one.',
        });
      }

      return res.status(200).json({
        success: true,
        data: { profile: null },
        message: 'No profile yet. Use POST /api/profile to create one.',
      });
    }

    res.status(200).json({
      success: true,
      data: { profile },
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message || 'Server error',
    });
  }
};

// Valid skill levels (must match StudentProfile schema)
const SKILL_LEVELS = ['beginner', 'intermediate', 'advanced', 'expert'];

// Validate and normalize a single skill object
const normalizeToolsList = (raw) => {
  if (Array.isArray(raw)) {
    return [...new Set(raw.map((t) => String(t || '').trim()).filter(Boolean))].slice(0, 50);
  }
  if (typeof raw === 'string') {
    return [
      ...new Set(
        raw
          .split(/[,;\n]+/)
          .map((t) => t.trim())
          .filter(Boolean)
      ),
    ].slice(0, 50);
  }
  return [];
};

const normalizeSkill = (s) => {
  if (!s || typeof s.name !== 'string' || !s.name.trim()) {
    return null;
  }
  const level = SKILL_LEVELS.includes(s.level) ? s.level : 'beginner';
  let progress = Number(s.progress);
  if (Number.isNaN(progress) || progress < 0) progress = 0;
  if (progress > 100) progress = 100;
  return { name: s.name.trim(), level, progress };
};

// Calculate overallScore as average of skill.progress values
const computeOverallScore = (skills) => {
  if (!Array.isArray(skills) || skills.length === 0) return null;
  const sum = skills.reduce((acc, s) => acc + (s.progress ?? 0), 0);
  return Math.round((sum / skills.length) * 100) / 100;
};

// @desc    Create student profile
// @route   POST /api/profile
// @access  Private (students only)
exports.createProfile = async (req, res) => {
  try {
    if (req.user.role !== 'student') {
      return res.status(403).json({
        success: false,
        message: 'Only students can create a student profile.',
      });
    }

    const existing = await StudentProfile.findOne({ user: req.user._id });
    if (existing) {
      return res.status(400).json({
        success: false,
        message: 'Profile already exists. Use PUT to update.',
      });
    }

    const {
      bio,
      skills,
      course,
      branch,
      year,
      semester,
      studentPhone,
      fatherName,
      motherName,
      fatherPhone,
      motherPhone,
      address,
      city,
      state,
      pincode,
      dateOfBirth,
      bloodGroup,
      toolsAndTechnologies,
      visibleToCompanies,
    } = req.body;

    const normalizedSkills = [];
    if (Array.isArray(skills)) {
      for (const s of skills) {
        const skill = normalizeSkill(s);
        if (skill) normalizedSkills.push(skill);
      }
    }

    const str = (v) => (typeof v === 'string' ? v.trim() : '');
    const contactCheck = validateStudentProfileContactFields({
      studentPhone,
      fatherPhone,
      motherPhone,
      pincode,
      dateOfBirth,
      fatherName,
      motherName,
    });
    if (!contactCheck.ok) {
      return res.status(400).json({
        success: false,
        message: contactCheck.errors.join(' '),
      });
    }
    const c = contactCheck.normalized;
    const profile = await StudentProfile.create({
      user: req.user._id,
      bio: str(bio),
      course: str(course),
      branch: str(branch),
      year: str(year),
      semester: str(semester),
      studentPhone: c.studentPhone ?? '',
      fatherName: c.fatherName ?? '',
      motherName: c.motherName ?? '',
      fatherPhone: c.fatherPhone ?? '',
      motherPhone: c.motherPhone ?? '',
      address: str(address),
      city: str(city),
      state: str(state),
      pincode: c.pincode ?? '',
      dateOfBirth: c.dateOfBirth ?? '',
      bloodGroup: str(bloodGroup),
      emergencyContactName: '',
      emergencyContactPhone: '',
      toolsAndTechnologies: normalizeToolsList(toolsAndTechnologies),
      visibleToCompanies:
        typeof visibleToCompanies === 'boolean' ? visibleToCompanies : true,
      skills: normalizedSkills,
    });

    const populated = await StudentProfile.findById(profile._id).populate(
      'user',
      USER_POPULATE_FIELDS
    );

    res.status(201).json({
      success: true,
      message: 'Profile created',
      data: { profile: populated },
    });
  } catch (err) {
    if (err.name === 'ValidationError') {
      const messages = Object.values(err.errors).map((e) => e.message);
      return res.status(400).json({
        success: false,
        message: messages.join(' '),
      });
    }
    res.status(500).json({
      success: false,
      message: err.message || 'Server error',
    });
  }
};

// @desc    Update student profile (bio, skills, stats)
// @route   PUT /api/profile
// @access  Private
exports.updateProfile = async (req, res) => {
  try {
    const {
      bio,
      skills,
      stats,
      course,
      branch,
      year,
      semester,
      studentPhone,
      fatherName,
      motherName,
      fatherPhone,
      motherPhone,
      address,
      city,
      state,
      pincode,
      dateOfBirth,
      bloodGroup,
      toolsAndTechnologies,
      visibleToCompanies,
    } = req.body;
    const updateFields = {};
    let normalizedSkills = null;

    const trimStr = (v) => (typeof v === 'string' ? v.trim() : '');

    if (bio !== undefined) updateFields.bio = trimStr(bio);
    if (course !== undefined) updateFields.course = trimStr(course);
    if (branch !== undefined) updateFields.branch = trimStr(branch);
    if (year !== undefined) updateFields.year = trimStr(year);
    if (semester !== undefined) updateFields.semester = trimStr(semester);
    const contactPick = {};
    for (const k of CONTACT_PROFILE_KEYS) {
      if (req.body[k] !== undefined) contactPick[k] = req.body[k];
    }
    if (Object.keys(contactPick).length) {
      const contactCheck = validateStudentProfileContactFields(contactPick);
      if (!contactCheck.ok) {
        return res.status(400).json({
          success: false,
          message: contactCheck.errors.join(' '),
        });
      }
      Object.assign(updateFields, contactCheck.normalized);
    }
    if (address !== undefined) updateFields.address = trimStr(address);
    if (city !== undefined) updateFields.city = trimStr(city);
    if (state !== undefined) updateFields.state = trimStr(state);
    if (bloodGroup !== undefined) updateFields.bloodGroup = trimStr(bloodGroup);
    updateFields.emergencyContactName = '';
    updateFields.emergencyContactPhone = '';
    if (toolsAndTechnologies !== undefined) {
      updateFields.toolsAndTechnologies = normalizeToolsList(toolsAndTechnologies);
    }
    if (visibleToCompanies !== undefined) {
      updateFields.visibleToCompanies = Boolean(visibleToCompanies);
    }
    if (skills !== undefined) {
      normalizedSkills = [];
      if (Array.isArray(skills)) {
        for (const s of skills) {
          const skill = normalizeSkill(s);
          if (skill) normalizedSkills.push(skill);
        }
      }
      updateFields.skills = normalizedSkills;
    }
    if (stats !== undefined) updateFields.stats = stats;

    if (normalizedSkills !== null) {
      const overallScore = computeOverallScore(normalizedSkills);
      updateFields.overallScore = overallScore;
      if (overallScore !== null) {
        updateFields.$push = {
          scoreHistory: { score: overallScore, date: new Date() },
        };
      }
    }

    const profile = await StudentProfile.findOneAndUpdate(
      { user: req.user._id },
      updateFields,
      { new: true, runValidators: true }
    ).populate('user', USER_POPULATE_FIELDS);

    if (!profile) {
      return res.status(404).json({
        success: false,
        message: 'Profile not found. Create a profile first.',
      });
    }

    res.status(200).json({
      success: true,
      message: 'Profile updated',
      data: { profile },
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message || 'Server error',
    });
  }
};

// @desc    Update only skills
// @route   PATCH /api/profile/skills
// @access  Private
exports.updateSkills = async (req, res) => {
  try {
    const { skills } = req.body;

    if (!Array.isArray(skills)) {
      return res.status(400).json({
        success: false,
        message: 'Please provide skills as an array.',
      });
    }

    const normalizedSkills = [];
    for (const s of skills) {
      const skill = normalizeSkill(s);
      if (skill) normalizedSkills.push(skill);
    }

    const overallScore = computeOverallScore(normalizedSkills);
    const updateFields = {
      skills: normalizedSkills,
      overallScore,
    };
    if (overallScore !== null) {
      updateFields.$push = {
        scoreHistory: { score: overallScore, date: new Date() },
      };
    }

    const profile = await StudentProfile.findOneAndUpdate(
      { user: req.user._id },
      updateFields,
      { new: true, runValidators: true }
    ).populate('user', USER_POPULATE_FIELDS);

    if (!profile) {
      return res.status(404).json({
        success: false,
        message: 'Profile not found. Create a profile first.',
      });
    }

    res.status(200).json({
      success: true,
      message: 'Skills updated',
      data: { profile },
    });
  } catch (err) {
    res.status(500).json({
      success: false,
      message: err.message || 'Server error',
    });
  }
};
